### ISSUE TITLE
Only for windows?

### ISSUE THREAD

**Issue by williamjmorenor** [Mauxx91/XML-Editor#1]
This app only run in Windows or can run in a unix like Fedora?

**Comment by Mauxx91** [comment]
Hi, if you download the source code and proceed to build XML-Editor will
run il linux-like platform.

**Comment by Mauxx91** [comment]
Clicca qui per leggerlo:
https://www.tomshw.it/hardware/nvidia-quadro-rtx-4000-turing-professionale-a-singolo-slot-e-meno-di-1000-dollari/r..
è 4
R3xx
